### ISSUE TITLE
The sampled data is not complete.

### ISSUE THREAD

**Issue by leslie-arch** [HKUST-KnowComp/CEQA#1]
The downloaded sample data is incomplete, and the project lacks many files that need to be read during training.and , the  scripts named sample_all_types_aser_xx.py can't generate them at all.

**Comment by marcos0318** [comment]
Hi could you please provide more details on which data is missing during training so that I can help you to figure out the problem?

**Comment by marcos0318** [comment]
Thank you for pointing out this issue; I have changed some of the absolute paths to relative paths to read the downloaded files properly. Meanwhile, I have commented on some outdated input files that are not needed but read. 

I think the code would very likely work for you right now. If you have further questions, please reach out to me with no hesitation. 

Best 
Jiaxin
